@jwtToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwibmFtZSI6InRlc3QiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWRtaW4iLCJ0ZWFjaGVyIl19LCJpYXQiOjE3MjA1MzYzNzAsImV4cCI6MTcyMDYyMjc3MH0.Qn7BUYZEaJ2haI48uo7TQwCU88GrtDi7BZ7ZoErqLsT5dy9u5q3F1TNUuwHM8hyoi5KtNxwlzNbcmuub2b4GDUMoSZ6R031fesIT7j3vlQjZXO9f_S15m--xk2gQwhFMnwIfeQ2B8ElRFsCj4P6hCmONN_l6_LoBf2ug47Ok14WNizBfHMCQ33FZA-UPNGB07_NIhDhwBuv4FlKHMLpHNsI3xDpwkJM8iTnIiz-nrB1VxSJzSoeTk0GxgkMOwO25McoyHiAeEP-RfJWBW1S6daxeCTM0_L68-tvtrAgxP8XfMLtAGwyGFEWa4UggMbJyRUytpM3HD9MkiR2BXQ1MEg

### ========= STUDENT =========
POST http://localhost:3000/students
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "first_name": "Michael",
    "last_name": "Stuart",
    "date_of_birth": "1999-05-14", 
    "street": "Flower Street",
    "number": 123,
    "city": "Old York",
    "phone_number": "12345-6789"
}


###
GET http://localhost:3000/students/a1790da6-e796-4157-a712-57af227bcc25
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/students
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/students
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    "50a1adb2-669b-41b9-8a00-8302b7d2b4df",
    "2fc5ae96-6458-4c7b-81db-14645b595588"
]

###
PATCH http://localhost:3000/students
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "id": "a1790da6-e796-4157-a712-57af227bcc25",
    "first_name": "Jon"
}

###
DELETE http://localhost:3000/students/a1790da6-e796-4157-a712-57af227bcc25
Authorization: Bearer {{jwtToken}}



### ========= TEACHER =========
POST http://localhost:3000/teachers
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "first_name": "Eveling",
    "last_name": "Morgan",
    "subject_specialization": ["math"],
    "date_of_birth": "1999-05-14", 
    "street": "Flower Street",
    "number": 123,
    "city": "Old York",
    "phone_number": "12345-6789"
}

###
GET http://localhost:3000/teachers/bdba0dd5-0eb0-4833-8382-118e4e43552a
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/teachers
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/teachers
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    "bdba0dd5-0eb0-4833-8382-118e4e43552a",
    "31c37ca9-65ae-4a55-95b9-b2bc1318264c"
]

###
PATCH http://localhost:3000/teachers
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "id": "bdba0dd5-0eb0-4833-8382-118e4e43552a",
    "subject_to_add": "science",
    "address": {
        "street": "Flower Street 2",
        "number": 1234,
        "city": "Old York 2"
    }
}

###
DELETE http://localhost:3000/teachers/bdba0dd5-0eb0-4833-8382-118e4e43552a
Authorization: Bearer {{jwtToken}}


### ========= CLASROOM =========
POST http://localhost:3000/classrooms
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "grade_level": "1st Grade",
    "start_date": "2023-02-01",
    "end_date": "2023-12-01"
}

###
GET http://localhost:3000/classrooms/986f33b3-ef5c-4874-8bd6-f06ab8230934
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/classrooms
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/classrooms
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    "986f33b3-ef5c-4874-8bd6-f06ab8230934",
    "a56cd610-6fa7-4f9d-88df-924fe9d2c879"
]

###
PATCH  http://localhost:3000/classrooms
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "id": "986f33b3-ef5c-4874-8bd6-f06ab8230934",
    "grade_level": "2st Grade"
}

###
DELETE http://localhost:3000/classrooms/986f33b3-ef5c-4874-8bd6-f06ab8230934
Authorization: Bearer {{jwtToken}}



### ========= Enrollment =========
POST http://localhost:3000/enrollments
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "student_id": "01f7cb15-783b-460a-ab78-0c7507c05aff",
    "class_id": "96f95438-bd5d-4402-9a5c-c9a37dfd973b",
    "enrollment_date": "2023-12-01",
    "status": "enrolled"
}

###
GET http://localhost:3000/enrollments/574315c6-9a23-4089-9961-bf042cab8da7
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/enrollments
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/enrollments
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    "574315c6-9a23-4089-9961-bf042cab8da7",
    "f6b26838-8129-4391-9078-ca88c91de1b9"
]

###
PATCH http://localhost:3000/enrollments
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "id": "574315c6-9a23-4089-9961-bf042cab8da7",
    "status": "completed"
}

###
DELETE http://localhost:3000/enrollments/f6b26838-8129-4391-9078-ca88c91de1b9
Authorization: Bearer {{jwtToken}}


### ========= Grade =========
POST http://localhost:3000/grades
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "student_id": "b297d858-d7b5-47ee-a250-48e11ab349af",
    "subject": "english",
    "exam": 8,
    "assignment": 7,
    "others": 9
}

###
GET http://localhost:3000/grades/888acb2c-d07c-4365-b31c-941d3c280075
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/grades
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/grades
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    "888acb2c-d07c-4365-b31c-941d3c280075",
    "5f43cbc7-6042-45e3-bacf-d5c953c84026"
]

###
PATCH http://localhost:3000/grades
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "id": "888acb2c-d07c-4365-b31c-941d3c280075",
    "exam": 4
}

###
DELETE http://localhost:3000/grades/5f43cbc7-6042-45e3-bacf-d5c953c84026



### ========= Authentication =========
POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "s123"
}



###
GET http://localhost:3000/auth
Authorization: Bearer {{jwtToken}}