### ========= STUDENT =========
POST http://localhost:3000/students
Content-Type: application/json

{
    "first_name": "Michael",
    "last_name": "Stuart",
    "date_of_birth": "1999-05-14", 
    "street": "Flower Street",
    "number": 123,
    "city": "Old York",
    "phone_number": "12345-6789"
}


###
GET http://localhost:3000/students/a1790da6-e796-4157-a712-57af227bcc25

###
GET http://localhost:3000/students

###
GET http://localhost:3000/students
Content-Type: application/json

[
    "50a1adb2-669b-41b9-8a00-8302b7d2b4df",
    "2fc5ae96-6458-4c7b-81db-14645b595588"
]

###
PATCH http://localhost:3000/students
Content-Type: application/json

{
    "id": "a1790da6-e796-4157-a712-57af227bcc25",
    "first_name": "Jon"
}

###
DELETE http://localhost:3000/students/a1790da6-e796-4157-a712-57af227bcc25



### ========= TEACHER =========
POST http://localhost:3000/teachers
Content-Type: application/json

{
    "first_name": "Eveling",
    "last_name": "Morgan",
    "subject_specialization": ["math"],
    "date_of_birth": "1999-05-14", 
    "street": "Flower Street",
    "number": 123,
    "city": "Old York",
    "phone_number": "12345-6789"
}

###
GET http://localhost:3000/teachers/bdba0dd5-0eb0-4833-8382-118e4e43552a

###
GET http://localhost:3000/teachers

###
GET http://localhost:3000/teachers
Content-Type: application/json

[
    "bdba0dd5-0eb0-4833-8382-118e4e43552a",
    "31c37ca9-65ae-4a55-95b9-b2bc1318264c"
]

###
PATCH http://localhost:3000/teachers
Content-Type: application/json

{
    "id": "bdba0dd5-0eb0-4833-8382-118e4e43552a",
    "subject_to_add": "science",
    "address": {
        "street": "Flower Street 2",
        "number": 1234,
        "city": "Old York 2"
    }
}

###
DELETE http://localhost:3000/teachers/bdba0dd5-0eb0-4833-8382-118e4e43552a


### ========= TEACHER =========
POST http://localhost:3000/classrooms
Content-Type: application/json

{
    "grade_level": "1st Grade",
    "start_date": "2023-02-01",
    "end_date": "2023-12-01"
}

###
GET http://localhost:3000/classrooms/986f33b3-ef5c-4874-8bd6-f06ab8230934

###
GET http://localhost:3000/classrooms

###
GET http://localhost:3000/classrooms
Content-Type: application/json

[
    "986f33b3-ef5c-4874-8bd6-f06ab8230934",
    "a56cd610-6fa7-4f9d-88df-924fe9d2c879"
]

###
PATCH  http://localhost:3000/classrooms
Content-Type: application/json

{
    "id": "986f33b3-ef5c-4874-8bd6-f06ab8230934",
    "grade_level": "2st Grade"
}

###
DELETE http://localhost:3000/classrooms/986f33b3-ef5c-4874-8bd6-f06ab8230934