version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: school_app
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data