version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./envs:/home/node/app/envs
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: school_app
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data