version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: school_app
    ports:
      - "5432:5432"
    volumes:
      - shcool_data:/var/lib/postgresql/data

volumes:
  shcool_data: