FROM node:20.5.1-slim as development

USER node

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

CMD [ "tail", "-f", "/dev/null" ]